remote_theme: arjunpejathaya/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Arjun Pejathaya
github_username:  arjunpejathaya
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

theme: jekyll-theme-slate